{
 "title": "todo_service_dashboard",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Requests per minute",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 11, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(rate(node_network_receive_bytes_total[1m])) by (instance)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Service Error rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 13, "x": 11, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(rate(service_errors_total[1m])) by (service, endpoint)",
     "legendFormat": "Service: {{service}}, Endpoint: {{endpoint}}"
    }
   ]
  },
  {
   "title": "Average Amount of CPU Time Spent in System Mode",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 11, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(node_cpu_seconds_total{mode=\"system\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Amount of Available Memory",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 13, "x": 11, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes * 100",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}